In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
veriler = pd.read_csv("veriler.csv")
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [3]:
# x-y değişkenlerinin belirlenmesi

x = veriler.iloc[:,1:4].values
y = veriler.iloc[:,4:].values
print(x)
print(y)

[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]
[['e']
 ['e']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['k']
 ['k']]


In [4]:
# train-test bölünmesi

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(x_train) # fit öğretmek, transform ise o öğretileni uygulamak
X_test = sc.transform(x_test)

In [6]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train, y_train)

y_pred = logr.predict(X_test)
print(y_pred)
print(y_test)

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


C:\Users\bilal\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [7]:
# Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm) # Doğru tahminler true-pos ve true-neg üzerinden bakılır
# accuracy = 1/8 ve error rate = 1 - acc = 7/8 hata oranı çok yüksek

[[0 1]
 [7 0]]


In [8]:
# KNN

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski') # komşu sayısını artırarak her zaman başarı oranını arttıramayız 
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
print(y_pred)
print(y_test)

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'k']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


C:\Users\bilal\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [9]:
# Confusion Matrix

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[0 1]
 [6 1]]


In [13]:
# SVC

from sklearn.svm import SVC
svc = SVC(kernel='rbf') # farklı parametreleri de deneyebiliriz
svc.fit(X_train, y_train)

y_pred = svc.predict(X_test)
print(y_pred)
print(y_test)

['e' 'k' 'e' 'e' 'e' 'e' 'e' 'k']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


C:\Users\bilal\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [14]:
# Confusion Matrix

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1 0]
 [5 2]]


In [15]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)
print(y_pred)
print(y_test)

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'k']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


C:\Users\bilal\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [16]:
# Confusion Matrix

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[0 1]
 [6 1]]


In [17]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy') # default parametre gini dir
dtc.fit(X_train, y_train)

y_pred = dtc.predict(X_test)
print(y_pred)
print(y_test)

['e' 'k' 'k' 'k' 'e' 'k' 'k' 'k']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


In [18]:
# Confusion Matrix

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1 0]
 [1 6]]


In [23]:
# Random Forrest

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10, criterion='entropy')
rfc.fit(X_train, y_train)

y_pred = rfc.predict(X_test)
print(y_pred)
print(y_test)

['e' 'k' 'k' 'k' 'e' 'k' 'k' 'e']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


C:\Users\bilal\AppData\Local\Temp/ipykernel_2812/1160844003.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X_train, y_train)


In [25]:
# Confusion Matrix

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1 0]
 [2 5]]
